#!/usr/bin/env node
// Writes <docs>/.open-work.md: the md files of the docs folder that open work (a branch with
// changes not yet in the default branch, with or without an open pull request) is changing.
// The page reads it to mark busy nodes, so it works offline (see docs/viewer/map/nodos-ocupados.md).
// Run by .github/workflows/open-work.yml; needs GITHUB_TOKEN and GITHUB_REPOSITORY.
//
//   node tools/open-work.mjs [docs folder] [--delete-merged]   (default: docs)
//
// --delete-merged also deletes branches whose pull request was merged and that have nothing new since.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';

const args = process.argv.slice(2);
const docsDir = resolve(args.find(a => !a.startsWith('--')) || 'docs');
const docs = basename(docsDir);
const deleteMerged = args.includes('--delete-merged');
const repo = process.env.GITHUB_REPOSITORY;
const token = process.env.GITHUB_TOKEN;
if (!repo || !token) throw new Error('GITHUB_REPOSITORY and GITHUB_TOKEN are needed');

async function gh(path, { method = 'GET', all = false } = {}) {
  const out = [];
  for (let url = `https://api.github.com/repos/${repo}${path}`; url;) {
    const res = await fetch(url, { method, headers: { authorization: `Bearer ${token}`, accept: 'application/vnd.github+json' } });
    if (method === 'DELETE') return res.ok;
    if (!res.ok) throw new Error(`${method} ${url}: ${res.status} ${await res.text()}`);
    const body = await res.json();
    if (!all) return body;
    out.push(...body);
    url = /<([^>]+)>;\s*rel="next"/.exec(res.headers.get('link') || '')?.[1];
  }
  return out;
}

const stamp = iso => iso.replace('T', ' ').slice(0, 16);
const THREAD_RE = /https:\/\/claude\.ai\/code\/project\/[^\s)\]>"']+/g;

const { default_branch: main } = await gh('');
const branches = (await gh('/branches?per_page=100', { all: true })).filter(b => b.name !== main);
const pulls = await gh('/pulls?state=all&per_page=100', { all: true });

const entries = [];
for (const { name: branch, commit: { sha } } of branches.sort((a, b) => a.name < b.name ? -1 : 1)) {
  const prs = pulls.filter(p => p.head.ref === branch && p.head.repo && p.head.repo.full_name === repo);
  const open = prs.find(p => p.state === 'open');
  // A closed pull request whose head is still the branch's head: that work is merged or dropped.
  const done = !open && prs.find(p => p.state === 'closed' && p.head.sha === sha);
  if (done) {
    if (deleteMerged && done.merged_at) {
      const ok = await gh(`/git/refs/heads/${encodeURIComponent(branch)}`, { method: 'DELETE' });
      console.log(`${ok ? 'Deleted' : 'Could not delete'} ${branch} (pull request #${done.number} merged).`);
    }
    continue;
  }
  const cmp = await gh(`/compare/${encodeURIComponent(main)}...${encodeURIComponent(branch)}`);
  if (!cmp.ahead_by) continue;
  const files = (cmp.files || [])
    .filter(f => f.filename.startsWith(docs + '/') && /\.md$/i.test(f.filename) && !basename(f.filename).startsWith('.'));
  const paths = new Set();
  for (const f of files) {
    paths.add(f.filename.slice(docs.length + 1));
    if (f.previous_filename && f.previous_filename.startsWith(docs + '/')) paths.add(f.previous_filename.slice(docs.length + 1));
  }
  if (!paths.size) continue;
  // The thread: the last `threads` link the branch adds to an md, else the one in the pull request's description.
  let thread = '';
  for (const f of files) for (const line of (f.patch || '').split('\n'))
    if (/^\+\s+-\s.*\|/.test(line)) thread = (line.match(THREAD_RE) || [thread]).pop();
  if (!thread && open) thread = ((open.body || '').match(THREAD_RE) || [''])[0];
  entries.push({
    branch,
    pr: open ? `#${open.number} · ${open.title.replace(/\s+/g, ' ')} · ${open.html_url}` : '',
    thread,
    since: cmp.commits.length ? stamp(cmp.commits[0].commit.committer.date) : '',
    files: [...paths].sort(),
  });
}

const head = [
  '# Open work',
  'Generated by `node tools/open-work.mjs` (GitHub workflow "Open work") from the branches and pull requests of the repository. Do not edit it by hand.',
];
const body = entries.flatMap(e => [
  '', `## ${e.branch}`,
  ...(e.pr ? [`- Pull request: ${e.pr}`] : []),
  ...(e.thread ? [`- Thread: ${e.thread}`] : []),
  ...(e.since ? [`- Since: ${e.since}`] : []),
  `- Files: ${e.files.join(', ')}`,
]);
const target = join(docsDir, '.open-work.md');
const old = existsSync(target) ? readFileSync(target, 'utf8') : null;
const withoutStamp = t => t.replace(/^Updated: .*\n/m, '');
const text = [...head, `Updated: ${stamp(new Date().toISOString())} UTC`, ...body, ''].join('\n');
if (old !== null && withoutStamp(old) === withoutStamp(text)) console.log(`${target}: no change (${entries.length} branches with open work).`);
else {
  writeFileSync(target, text);
  console.log(`Wrote ${target} (${entries.length} branches with open work).`);
}
